name: Lint HTML & CSS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install -g stylelint stylelint-config-standard

      - name: Ensure Stylelint Config Exists
        run: |
          if [ ! -f .stylelintrc.json ]; then
            echo '{ "extends": "stylelint-config-standard", "rules": { "indentation": 2, "color-no-invalid-hex": true } }' > .stylelintrc.json
          fi

      - name: Run Stylelint
        run: stylelint "**/*.css"
